### ISSUE TITLE
Замечания по FindPointer

### ISSUE THREAD

**Issue by sergey-shambir** [Warboss-rus/metaprogrammingcourse#1]
1) Функция GetPointer использует нестандартное поле, что может создать проблемы переносимости на другие компиляторы
```cpp
template<class Iterator>
auto GetPointer(Iterator it)
{
	return it._Ptr;
}
```
Например на GCC валится: https://wandbox.org/permlink/NmHpo5uMx8aFYzlr
2) В заголовке `FindPointer.h` используется [std::invoke](http://en.cppreference.com/w/cpp/utility/functional/invoke), значит, стоит подключить заголовок `<functional>`
3) Аналогично, [std::iterator_traits](http://en.cppreference.com/w/cpp/iterator/iterator_traits) требует заголовка `<iterator>` - нет гарантии, что другие заголовки будут его включать

**Comment by Warboss-rus** [comment]
Поправил, проверил сборку на clang и gcc
https://godbolt.org/g/98KurS
