### ISSUE TITLE
Замечания по MovableFunction

### ISSUE THREAD

**Issue by sergey-shambir** [Warboss-rus/metaprogrammingcourse#2]
1) Такой static_assert не сработает правильно, первый аргумент превратится в `true`:
```cpp
static_assert("Cannot copy");
```
2) Здесь не хватает universal reference для parameter pack:
```cpp
template<class... Args>
ReturnType operator()(Args... args) const
```

**Comment by Warboss-rus** [comment]
Поправлено.
К сожалению узнать можем ли мы скопировать функтор мы можем только в рантайме. Заменил ассерт на выброс исключения.
Проверка в GCC+Clang: https://godbolt.org/g/ibbGAm

**Comment by sergey-shambir** [comment]
Нет, если стоит `if constexpr`, значит, узнать можно в compile-time. Другой вопрос, что компиляция constexpr if может состоять из нескольких шагов.
Это значит, что `static_assert(false, "...")` обвалит компиляцию, но если результат static_assert зависит от типа T (от которого зависит и условие), то не обвалит.
Можно использовать заведомо ложное условие, например, `static_assert(!is_same_v<T, T>, "...")`.

**Comment by Warboss-rus** [comment]
Узнать в compile-time мы можем только в MovableFunctionImpl, а значит только в рантайме (в одной MovableFunction может лежать либо копируемый функтор, либо некопируемый. Добавил тест на выбрасывание исключения при копировании MovableFunction с некопируемым функтором, поправил оператор присваивания (забыл return *this)

**Comment by sergey-shambir** [comment]
Предлагаю в таком случае убрать клонирование и копирование вообще - пусть MovableFunction будет movable-only.

**Comment by Warboss-rus** [comment]
Выпилил
